return {
  {
    "nvim-treesitter/nvim-treesitter",
    version = false,
    build = ":TSUpdate",
    opts = {
      ensure_installed = {
        "astro",
        "bash",
        "c",
        "c_sharp",
        "clojure",
        "cmake",
        "comment",
        "commonlisp",
        "cpp",
        "css",
        "cue",
        "d",
        "dart",
        "dhall",
        "diff",
        "dockerfile",
        "dot",
        "elixir",
        "elm",
        "erlang",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitignore",
        "gitcommit",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "graphql",
        "hcl",
        "html",
        "ini",
        "java",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "jsonnet",
        "kotlin",
        "latex",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "nix",
        "ocaml",
        "objc",
        "passwd",
        "perl",
        "php",
        "phpdoc",
        "po",
        "proto",
        "puppet",
        "python",
        "qmldir",
        "qmljs",
        "query",
        "regex",
        "rego",
        "ruby",
        "rust",
        "scala",
        "scheme",
        "scss",
        "sql",
        "surface",
        "svelte",
        "swift",
        "tablegen",
        "terraform",
        "todotxt",
        "toml",
        "tsx",
        "twig",
        "typescript",
        "vala",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
        "zig",
      },
      highlight = {
        enable = true,
      },
      indent = {
        enable = true,
        disable = {
          "yaml",
        },
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
      textobjects = {
        move = {
          enable = true,
          goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer" },
          goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer" },
          goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer" },
          goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer" },
        },
      },
    },
    config = function(_, opts)
      require('nvim-treesitter.install').prefer_git = true
      ---@diagnostic disable-next-line: missing-fields
      require('nvim-treesitter.configs').setup(opts)
    end,
    legendary = {
      commands = {
        {
          ":TSInstall <language>",
          description = "Install Treesitter parser for <language>",
          unfinished = true,
        },
        {
          ":TSInstallInfo",
          description = "Print available languages and their installation status.",
        },
        {
          ":TSUpdate <language>",
          description = "Update parser for <language> or 'all'.",
          unfinished = true,
        },
      },
    },
  },
}
